let stacks = parseInt(prompt("Input a number 1 - 8"))
if(stacks <= 0 ||stacks >=  9) 
    console.log("invalid number")
if(stacks > 0) 
    console.log("       #")
if(stacks > 1) 
    console.log("\n      ##") 
if(stacks > 2) 
    console.log("\n     ###") 
if(stacks > 3) 
    console.log("\n    ####") 
if(stacks > 4) 
    console.log("\n   #####") 
if(stacks > 5) 
    console.log("\n  ######") 
if(stacks > 6) 
    console.log("\n #######") 
if(stacks > 6) 
    console.log("\n########") 
// its just an if statement copied and pasted and altered a bit lol
